import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import { ReactNode } from 'react';
import './fontawesome';
import { Providers } from './providers';
import { cookieToInitialState, type State } from 'wagmi';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Game Project',
  description: 'Generated by Abhishek',
};

export default function RootLayout(props: { children: ReactNode }) {
  const cookies = headers().get('cookie') || '';

  const initialState: any = cookieToInitialState(cookies)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>{props.children}</Providers>
      </body>
    </html>
  );
}
